apiVersion: apps/v1
kind: Deployment
metadata:
  name: fad-app
  namespace: fadgw
  labels:
    app: fad-app
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: fad-app
  template:
    metadata:
      labels:
        deployment: fad-app
    spec:
      containers:
      - env:
        - name: service_name
          value: fad-app
        image: hsandy123/simpleserver:1.0.0-002
        imagePullPolicy: Always
        name: fad-app
        ports:
        - containerPort: 1234
          protocol: TCP
